### ISSUE TITLE
Where is the docker file?

### ISSUE THREAD

**Issue by nickjuntilla** [enKryptIO/ethvm#14]
* **I'm submitting a ...**
    - [ ] bug report

* **Bug Report**
 I see the command in the readme to run "docker-compose up -d", but where do we run it? Where do we get the docker file?

**Comment by niktrix** [comment]
It is moved to https://github.com/enKryptIO/ethvm-dev-kit, which is still in WIP state, and Readme will be updated soon

**Comment by nickjuntilla** [comment]
Ok thanks. I'm trying to run the docker container. I'm on Ubuntu 18.4 LTS. I have docker-compose version 1.22.0. I'm getting this error after I run `sudo docker-compose --verbose up -d`

```
sudo docker-compose --verbose up -d
compose.config.config.find: Using configuration files: ./docker-compose.yaml
docker.utils.config.find_config_file: Trying paths: ['/home/worldnick/.docker/config.json', '/home/worldnick/.dockercfg']
docker.utils.config.find_config_file: No config file found
docker.utils.config.find_config_file: Trying paths: ['/home/worldnick/.docker/config.json', '/home/worldnick/.dockercfg']
docker.utils.config.find_config_file: No config file found
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.36/version HTTP/1.1" 400 84
Traceback (most recent call last):
  File "site-packages/docker/api/client.py", line 229, in _raise_for_status
  File "site-packages/requests/models.py", line 935, in raise_for_status
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.36/version

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 71, in main
  File "compose/cli/main.py", line 124, in perform_command
  File "compose/cli/command.py", line 41, in project_from_options
  File "compose/cli/command.py", line 121, in get_project
  File "compose/cli/command.py", line 95, in get_client
  File "site-packages/docker/api/daemon.py", line 181, in version
  File "site-packages/docker/api/client.py", line 235, in _result
  File "site-packages/docker/api/client.py", line 231, in _raise_for_status
  File "site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
docker.errors.APIError: 400 Client Error: Bad Request ("client version 1.36 is too new. Maximum supported API version is 1.35")
[29768] Failed to execute script docker-compose
```

**Comment by aldoborrero** [comment]
@nickjuntilla It seems you need to update docker and docker-compose or lower down the compose file version to 3.5 instead of 3.6 (the one we're using).

[More information](https://www.reddit.com/r/docker/comments/8nugyh/error_client_version_136_is_too_new_maximum/)
