### ISSUE TITLE
Exception on Kafka Processing

### ISSUE THREAD

**Issue by aldoborrero** [enKryptIO/ethvm#259]
From time to time, if I destroy the docker environment with everything (including volumes), whenever I process again a new downloaded chain, I obtain this issue:

'''
Aldo Borrero, [22.01.19 21:37]
16:13:41.185 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 0
16:13:42.169 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 1
16:13:42.204 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 2
16:13:42.218 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 3
16:13:42.341 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 4
16:13:42.364 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 5
16:13:42.377 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 6
16:13:42.380 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 7
16:13:42.415 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 8
16:13:42.417 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 9
16:13:42.421 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 10
16:13:42.423 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 11
16:13:42.428 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 12
16:13:42.432 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 13
16:13:42.443 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 14
16:13:42.452 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 15
16:13:42.459 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 16
16:13:42.460 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 17
16:13:42.462 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 18
16:13:42.467 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 19
16:13:42.469 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 20
16:13:42.471 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 21
16:13:42.474 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 22
16:13:42.476 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 23
16:13:42.479 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 24
16:13:42.491 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 25
16:13:42.509 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 26
16:13:42.511 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 27
16:13:42.512 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 28
16:13:42.514 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 29
16:13:42.516 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 30
16:13:42.517 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 31
16:13:42.519 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 32
16:13:42.520 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 33
16:13:42.524 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 34
16:13:42.525 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 35
16:13:42.530 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 36
16:13:42.532 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 37
16:13:42.535 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 38
16:13:42.538 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 39
16:13:42.540 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 40
16:13:42.542 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 41
16:13:42.544 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 42
16:13:42.552 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 43
16:13:42.553 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 44
16:13:42.553 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 45
16:13:42.563 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 46
16:13:42.565 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 47

Aldo Borrero, [22.01.19 21:37]
16:13:42.566 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 48
16:13:42.568 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 49
16:13:42.569 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 50
16:13:42.570 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 51
16:13:42.571 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 52
16:13:42.573 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 53
16:13:42.575 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 54
16:13:42.576 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 55
16:13:42.577 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 56
16:13:42.578 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 57
16:13:42.579 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 58
16:13:42.580 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 59
16:13:42.581 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 60
16:13:42.583 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 61
16:13:42.585 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 62
16:13:42.587 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 63
16:13:42.589 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 64
16:13:42.591 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 65
16:13:42.599 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 66
16:13:42.601 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 67
16:13:42.619 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 68
16:13:42.625 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 69
16:13:42.641 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 70
16:13:42.643 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 71
16:13:42.648 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 72
16:13:42.650 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 73
16:13:42.653 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 74
16:13:42.655 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 75
16:13:42.676 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 76
16:13:42.706 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 77
16:13:42.721 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 78
16:13:42.731 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 79
16:13:42.734 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 80
16:13:42.736 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 81
16:13:42.742 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 82
16:13:42.745 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 83
16:13:42.760 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 84
16:13:42.766 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 85
16:13:42.768 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 86
16:13:42.769 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 87
16:13:42.771 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 88
16:13:42.772 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 89
16:13:42.774 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 90
16:13:42.775 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 91
16:13:42.776 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 92
16:13:42.778 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 93
16:13:42.779 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 94
16:13:42.780 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 95

Aldo Borrero, [22.01.19 21:37]
16:13:42.781 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 96
16:13:42.786 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 97
16:13:42.788 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 98
16:13:42.790 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 99
16:13:42.813 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 100
16:13:42.820 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 101
16:13:42.826 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 102
16:13:42.828 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 103
16:13:42.831 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 104
16:13:42.833 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 105
16:13:42.835 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 106
16:13:42.836 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 107
16:13:42.841 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 108
16:13:42.845 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 109
16:13:42.859 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 110
16:13:42.868 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 111
16:13:42.871 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 112
16:13:42.875 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 113
16:13:42.877 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 114
16:13:42.881 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 115
16:13:42.885 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 116
16:13:42.887 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 117
16:13:42.891 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 118
16:13:42.899 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 119
16:13:42.912 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 120
16:13:42.923 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 121
16:13:42.927 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 122
16:13:42.929 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 123
16:13:42.932 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 124
16:13:42.936 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 125
16:13:42.939 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 126
16:13:42.944 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 127
16:13:42.972 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 128
16:13:42.977 WARN  i.e.k.s.p.b.ChainEventsTransformer - Ignoring block 128, already processed
16:13:42.978 INFO  i.e.k.s.processors.BlockProcessor - Processing block number = 129
16:13:42.982 ERROR o.a.k.s.p.i.AssignedStreamsTasks - stream-thread [block-processor-1fe1a9ba-e648-4bc0-a02d-78e567ba37aa-StreamThread-1] Failed to process stream task 0_0 due to the following error:
java.lang.IllegalStateException: Block out of sequence. Expected = 128, received = 129
  at io.enkrypt.kafka.streams.processors.block.ChainEventsTransformer.ensureSequentialProcessing(ChainEventsTransformer.kt:103)
  at io.enkrypt.kafka.streams.processors.block.ChainEventsTransformer.transform(ChainEventsTransformer.kt:88)
  at io.enkrypt.kafka.streams.processors.block.ChainEventsTransformer.transform(ChainEventsTransformer.kt:25)
  at org.apache.kafka.streams.kstream.internals.KStreamTransform$KStreamTransformProcessor.process(KStreamTransform.java:56)
  at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:115)
  at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:146)
  at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:132)

Aldo Borrero, [22.01.19 21:37]
at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:93)
  at org.apache.kafka.streams.kstream.internals.KStreamPeek$KStreamPeekProcessor.process(KStreamPeek.java:44)
  at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:115)
  at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:146)
  at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:129)
  at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:93)
  at org.apache.kafka.streams.processor.internals.SourceNode.process(SourceNode.java:84)
  at org.apache.kafka.streams.processor.internals.StreamTask.process(StreamTask.java:351)
  at org.apache.kafka.streams.processor.internals.AssignedStreamsTasks.process(AssignedStreamsTasks.java:104)
  at org.apache.kafka.streams.processor.internals.TaskManager.process(TaskManager.java:413)
  at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:862)
  at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:777)
  at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:747)
16:13:42.982 ERROR o.a.k.s.p.internals.StreamThread - stream-thread [block-processor-1fe1a9ba-e648-4bc0-a02d-78e567ba37aa-StreamThread-1] Encountered the following error during processing:
java.lang.IllegalStateException: Block out of sequence. Expected = 128, received = 129
  at io.enkrypt.kafka.streams.processors.block.ChainEventsTransformer.ensureSequentialProcessing(ChainEventsTransformer.kt:103)
  at io.enkrypt.kafka.streams.processors.block.ChainEventsTransformer.transform(ChainEventsTransformer.kt:88)
  at io.enkrypt.kafka.streams.processors.block.ChainEventsTransformer.transform(ChainEventsTransformer.kt:25)
  at org.apache.kafka.streams.kstream.internals.KStreamTransform$KStreamTransformProcessor.process(KStreamTransform.java:56)
  at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:115)
  at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:146)
  at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:132)
  at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:93)
  at org.apache.kafka.streams.kstream.internals.KStreamPeek$KStreamPeekProcessor.process(KStreamPeek.java:44)
  at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:115)
  at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:146)
  at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:129)
  at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:93)
  at org.apache.kafka.streams.processor.internals.SourceNode.process(SourceNode.java:84)
  at org.apache.kafka.streams.processor.internals.StreamTask.process(StreamTask.java:351)
  at org.apache.kafka.streams.processor.internals.AssignedStreamsTasks.process(AssignedStreamsTasks.java:104)
  at org.apache.kafka.streams.processor.internals.TaskManager.process(TaskManager.java:413)
  at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:862)
  at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:777)
  at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:747)

Aldo Borrero, [22.01.19 21:37]
16:13:43.024 ERROR o.a.k.s.p.i.RecordCollectorImpl - task [0_0] Error sending record (key \x00\x00\x00\x00\x05\x02p|\xF0\x06\xB7\x10Ih\xEC\xC9\x08\x94,\x03\xFF\xCA[\x13J+\xDA\xEE\x1C\x1E\x83\xA2\xA3\xA3\xAA\x85\x91\xED\x00\x00\x00\x00\x00 value [0, 0, 0, 0, 6, 2, 2, 0, 2, 27, 112, 71, -76, 51, -118, -49, 101, -66, -108, -63, -93, -24, -59, -55, 51, -118, -41, -42, 124, 16, 69, 99, -111, -126, 68, -12, 0, 0, 0, 0] timestamp 1548202124660) to topic block-processor-chain-events-changelog due to org.apache.kafka.common.KafkaException: Failing batch since transaction was aborted; No more records will be sent and no more offsets will be recorded for this task.
16:13:43.056 ERROR o.a.k.s.p.internals.StreamTask - task [0_0] Failed to close producer due to the following error:
org.apache.kafka.streams.errors.StreamsException: task [0_0] Abort sending since an error caught with a previous record (key \x00\x00\x00\x00\x05\x02p|\xF0\x06\xB7\x10Ih\xEC\xC9\x08\x94,\x03\xFF\xCA[\x13J+\xDA\xEE\x1C\x1E\x83\xA2\xA3\xA3\xAA\x85\x91\xED\x00\x00\x00\x00\x00 value [B@22a4ed8 timestamp 1548202124660) to topic block-processor-chain-events-changelog due to org.apache.kafka.common.KafkaException: Failing batch since transaction was aborted
  at org.apache.kafka.streams.processor.internals.RecordCollectorImpl.recordSendError(RecordCollectorImpl.java:133)
  at org.apache.kafka.streams.processor.internals.RecordCollectorImpl.access$500(RecordCollectorImpl.java:50)
  at org.apache.kafka.streams.processor.internals.RecordCollectorImpl$1.onCompletion(RecordCollectorImpl.java:192)
  at org.apache.kafka.clients.producer.KafkaProducer$InterceptorCallback.onCompletion(KafkaProducer.java:1288)
  at org.apache.kafka.clients.producer.internals.ProducerBatch.completeFutureAndFireCallbacks(ProducerBatch.java:230)
  at org.apache.kafka.clients.producer.internals.ProducerBatch.abort(ProducerBatch.java:158)
  at org.apache.kafka.clients.producer.internals.RecordAccumulator.abortUndrainedBatches(RecordAccumulator.java:762)
  at org.apache.kafka.clients.producer.internals.Sender.maybeSendTransactionalRequest(Sender.java:396)
  at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:284)
  at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:233)
  at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.common.KafkaException: Failing batch since transaction was aborted
  ... 4 common frames omitted
Exception in thread "block-processor-1fe1a9ba-e648-4bc0-a02d-78e567ba37aa-StreamThread-1" java.lang.IllegalStateException: Block out of sequence. Expected = 128, received = 129
  at io.enkrypt.kafka.streams.processors.block.ChainEventsTransformer.ensureSequentialProcessing(ChainEventsTransformer.kt:103)
  at io.enkrypt.kafka.streams.processors.block.ChainEventsTransformer.transform(ChainEventsTransformer.kt:88)
  at io.enkrypt.kafka.streams.processors.block.ChainEventsTransformer.transform(ChainEventsTransformer.kt:25)
  at org.apache.kafka.streams.kstream.internals.KStreamTransform$KStreamTransformProcessor.process(KStreamTransform.java:56)
  at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:115)
  at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:146)
  at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:132)
  at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:93)
  at org.apache.kafka.streams.kstream.internals.KStreamPeek$KStreamPeekProcessor.process(KStreamPeek.java:44)
  at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:115)
  at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:146)
  at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:129)
  at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:93)

Aldo Borrero, [22.01.19 21:37]
at org.apache.kafka.streams.processor.internals.SourceNode.process(SourceNode.java:84)
  at org.apache.kafka.streams.processor.internals.StreamTask.process(StreamTask.java:351)
  at org.apache.kafka.streams.processor.internals.AssignedStreamsTasks.process(AssignedStreamsTasks.java:104)
  at org.apache.kafka.streams.processor.internals.TaskManager.process(TaskManager.java:413)
  at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:862)
  at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:777)
  at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:747)
16:13:43.109 WARN  o.apache.kafka.streams.KafkaStreams - stream-client [block-processor-1fe1a9ba-e648-4bc0-a02d-78e567ba37aa] All stream threads have died.
'''

**Comment by brianmcgee** [comment]
This is caused by a bad encoding of the block number in ethereumj, using signed instead of unsigned big integer format
