### ISSUE TITLE
Remove warnings

### ISSUE THREAD

**Issue by aldoborrero** [enKryptIO/ethvm#43]
Currently when compiling I'm obtaining these warnings:

```sh
Module Warning (from ./node_modules/eslint-loader/index.js):
ethvm_1       | error: Expected to return a value in "changeDescription" computed property (vue/return-in-computed-property) at src/components/blocks/smallBlocks/charts/topMiners.vue:66:22:
ethvm_1       |   64 |   computed: {
ethvm_1       |   65 |     /*Method to change description string: */
ethvm_1       | > 66 |     changeDescription() {
ethvm_1       |      |                      ^
ethvm_1       |   67 |       if (stateChanged && currentState == STATES.BEGIN) {
ethvm_1       |   68 |         description = DES.BEGIN + currentState
ethvm_1       |   69 |       } else if (stateChanged && currentState != STATES.BEGIN) {
ethvm_1       |
ethvm_1       |
ethvm_1       | 1 error found.
ethvm_1       |
ethvm_1       | Module Warning (from ./node_modules/eslint-loader/index.js):
ethvm_1       | error: Parsing error: x-invalid-end-tag (vue/no-parsing-error) at src/components/blocks/smallBlocks/charts/vuechart.vue:4:145:
ethvm_1       |   2 |   <div class="chart-container">
ethvm_1       |   3 |     <div class="chart-title-1">
ethvm_1       | > 4 |       <p>{{chartTitle}}<div class="tooltip-button" v-tooltip="chartDescription"><i class="fa fa-question-circle-o" aria-hidden="true"></i></div></p>
ethvm_1       |     |                                                                                                                                                 ^
ethvm_1       |   5 |     </div>
ethvm_1       |   6 |
ethvm_1       |   7 |     <div class="chart">
ethvm_1       |
ethvm_1       |
ethvm_1       | 1 error found.
ethvm_1       |
ethvm_1       | Module Warning (from ./node_modules/eslint-loader/index.js):
ethvm_1       | error: Unexpected side effect in "getTotalTokens" computed property (vue/no-side-effects-in-computed-properties) at src/components/blocks/largeBlocks/tokenTracker.vue:69:11:
ethvm_1       |   67 |       this.tokens.forEach(token => {
ethvm_1       |   68 |         if (this.checkBalance(token.balance)) {
ethvm_1       | > 69 |           this.totalTokens++
ethvm_1       |      |           ^
ethvm_1       |   70 |         }
ethvm_1       |   71 |       })
ethvm_1       |   72 |       return this.totalTokens
ethvm_1       |
ethvm_1       |
ethvm_1       | error: Unexpected side effect in "getTotalUSDValue" computed property (vue/no-side-effects-in-computed-properties) at src/components/blocks/largeBlocks/tokenTracker.vue:78:9:
ethvm_1       |   76 |       const usd = 0
ethvm_1       |   77 |       this.tokens.forEach(token => {
ethvm_1       | > 78 |         this.totalUSDValue += this.getBalance(token.balance, token.decimals) * token.USDValue
ethvm_1       |      |         ^
ethvm_1       |   79 |       })
ethvm_1       |   80 |       return this.formatUSDBalance(this.totalUSDValue)
ethvm_1       |   81 |     }
```

This task should take care of removing this messages.

**Comment by olgakup** [comment]
I think hsurf22 is very busy at this moment, i will take care of this sometime this week!

**Comment by aldoborrero** [comment]
Hey @niktrix as we talked this morning, just double check if you find more warnings on the frontend and remove those. Coordinate with @olgakup if find something that is not straightforward.
